### ISSUE TITLE
Failed to test:compile on Windows

### ISSUE THREAD

**Issue by tkawachi** [tkawachi/sbt-doctest#115]
I recently got a Windows PC and tried to build this project, but it failed. It's the first time of compiling Scala project on this PC, so it might be a problem of my environment.

```
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from D:\tmp\sbt-doctest\project
[info] Updating ProjectRef(uri("file:/D:/tmp/sbt-doctest/project/"), "sbt-doctest-build")...
[info] Done updating.
[info] Loading settings from build.sbt,publish.sbt,scripted.sbt,version.sbt ...
[info] Set current project to sbt-doctest (in build file:/D:/tmp/sbt-doctest/)
[info] Updating ProjectRef(uri("file:/D:/tmp/sbt-doctest/"), "root")...
[info] Formatting 6 Scala sources ProjectRef(uri("file:/D:/tmp/sbt-doctest/"), "root")(test) ...
[info] Done updating.
[info] Formatting 23 Scala sources ProjectRef(uri("file:/D:/tmp/sbt-doctest/"), "root")(compile) ...
[info] Compiling 23 Scala sources to D:\tmp\sbt-doctest\target\scala-2.12\sbt-1.0\classes ...
[info] Done compiling.
[error] java.lang.ExceptionInInitializerError
[error]         at com.github.tkawachi.doctest.DoctestPlugin$.doctestScaladocGenTests(DoctestPlugin.scala:57)
[error]         at com.github.tkawachi.doctest.DoctestPlugin$.$anonfun$doctestGenSettings$9(DoctestPlugin.scala:99)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
[error]         at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[error]         at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[error]         at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$4(Mirrors.scala:54)
[error]         at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:54)
[error]         at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[error]         at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage$lzycompute(Definitions.scala:169)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage(Definitions.scala:169)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass$lzycompute(Definitions.scala:170)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass(Definitions.scala:170)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1424)
[error]         at scala.tools.nsc.Global$Run.<init>(Global.scala:1158)
[error]         at scala.tools.nsc.doc.DocParser.<init>(DocParser.scala:23)
[error]         at scala.tools.nsc.doc.DocParser.<init>(DocParser.scala:19)
[error]         at com.github.tkawachi.doctest.ScaladocExtractor.<init>(ScaladocExtractor.scala:13)
[error]         at com.github.tkawachi.doctest.ScaladocTestGenerator$.<init>(ScaladocTestGenerator.scala:10)
[error]         at com.github.tkawachi.doctest.ScaladocTestGenerator$.<clinit>(ScaladocTestGenerator.scala)
[error]         at com.github.tkawachi.doctest.DoctestPlugin$.doctestScaladocGenTests(DoctestPlugin.scala:57)
[error]         at com.github.tkawachi.doctest.DoctestPlugin$.$anonfun$doctestGenSettings$9(DoctestPlugin.scala:99)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (doctestGenTests) java.lang.ExceptionInInitializerError
[error] Total time: 8 s, completed 2018/08/18 13:50:13
```

**Comment by tkawachi** [comment]
It compiles if I commented sbt-doctest from plugins.sbt. It seems to have an issue on Windows.
