### ISSUE TITLE
sbt-doctest version > 0.8.0 do not work with fresh sbt projects

### ISSUE THREAD

**Issue by ciuncan** [tkawachi/sbt-doctest#137]
I tried to integrate `sbt-doctest` into my scala repository but it fails with following error:

```
[error] java.lang.NoClassDefFoundError: scala/meta/prettyprinters/Options
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

I tried to isolate the error by removing other plugins (scalafmt, sbt-bloop etc.), downgrading sbt to 1.2.8, but to no avail. I tried different versions of `sbt-doctest`, only 0.8.0 worked (I didn't try lower versions), 0.9.0 and upwards fail at startup with the same error message.

I tried to reproduce the issue by creating a new sbt project using `sbt new scala/scala-seed.g8`, but gave the same error.

<details>
  <summary>
    Detailed error message with 1.2.8:
  </summary>

```
[error] sbt.internal.IncompatiblePluginsException: Binary incompatibility in plugins detected.
[error] Note that conflicts were resolved for some dependencies:
[error] 	org.scalameta:scalameta_2.12
[error] 	org.scalameta:transversers_2.12
[error] 	org.scalameta:quasiquotes_2.12
[error] 	org.scalameta:parsers_2.12
[error] 	org.scalameta:trees_2.12
[error] 	org.scalameta:tokenizers_2.12
[error] 	org.scalameta:tokens_2.12
[error] 	org.scalameta:inputs_2.12
[error] 	org.scalameta:io_2.12
[error] 	org.scalameta:dialects_2.12
[error] 	org.scalameta:common_2.12
[error] 	com.google.protobuf:protobuf-java
[error] 	com.lihaoyi:fastparse_2.12
[error] 	com.lihaoyi:fastparse-utils_2.12
[error] 	com.lihaoyi:sourcecode_2.12
[error] 	org.scalameta:semantic_2.12
[error] 	com.trueaccord.scalapb:scalapb-runtime_2.12
[error] 	com.trueaccord.lenses:lenses_2.12
[error] 	org.scalameta:inline_2.12
[error] 	com.lihaoyi:scalaparse_2.12
[error] 	org.scala-lang.modules:scala-parser-combinators_2.12
[error] 	org.scala-sbt:librarymanagement-core_2.12
[error] 	org.scala-lang.modules:scala-xml_2.12
[error] 	org.scala-sbt:util-tracking_2.12
[error] 	org.scala-sbt:launcher-interface
[error] 	org.scala-sbt:util-cache_2.12
[error] 	org.scala-sbt:util-logging_2.12
[error] 	org.scala-sbt:util-interface
[error] 	org.scala-sbt:util-control_2.12
[error] 	org.scala-sbt:io_2.12
[error] 	org.scala-sbt:util-relation_2.12
[error] 	org.scala-sbt:util-position_2.12
[error] 	at sbt.internal.PluginDiscovery$.incompatiblePlugins(PluginDiscovery.scala:182)
[error] 	at sbt.internal.PluginDiscovery$.loadModules(PluginDiscovery.scala:166)
[error] 	at sbt.internal.PluginDiscovery$.binarySourceModules(PluginDiscovery.scala:151)
[error] 	at sbt.internal.PluginDiscovery$.discover$1(PluginDiscovery.scala:43)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:55)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1318)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1263)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1225)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.NoClassDefFoundError: scala/meta/prettyprinters/Options
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.map(Stream.scala:414)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObjects(ModuleUtilities.scala:31)
[error] 	at sbt.internal.PluginDiscovery$.loadModules(PluginDiscovery.scala:161)
[error] 	at sbt.internal.PluginDiscovery$.binarySourceModules(PluginDiscovery.scala:151)
[error] 	at sbt.internal.PluginDiscovery$.discover$1(PluginDiscovery.scala:43)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:55)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1318)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1263)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1225)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.ClassNotFoundException: scala.meta.prettyprinters.Options
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.map(Stream.scala:414)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObjects(ModuleUtilities.scala:31)
[error] 	at sbt.internal.PluginDiscovery$.loadModules(PluginDiscovery.scala:161)
[error] 	at sbt.internal.PluginDiscovery$.binarySourceModules(PluginDiscovery.scala:151)
[error] 	at sbt.internal.PluginDiscovery$.discover$1(PluginDiscovery.scala:43)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:55)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1318)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1263)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1225)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.internal.IncompatiblePluginsException: Binary incompatibility in plugins detected.
[error] Note that conflicts were resolved for some dependencies:
[error] 	org.scalameta:scalameta_2.12
[error] 	org.scalameta:transversers_2.12
[error] 	org.scalameta:quasiquotes_2.12
[error] 	org.scalameta:parsers_2.12
[error] 	org.scalameta:trees_2.12
[error] 	org.scalameta:tokenizers_2.12
[error] 	org.scalameta:tokens_2.12
[error] 	org.scalameta:inputs_2.12
[error] 	org.scalameta:io_2.12
[error] 	org.scalameta:dialects_2.12
[error] 	org.scalameta:common_2.12
[error] 	com.google.protobuf:protobuf-java
[error] 	com.lihaoyi:fastparse_2.12
[error] 	com.lihaoyi:fastparse-utils_2.12
[error] 	com.lihaoyi:sourcecode_2.12
[error] 	org.scalameta:semantic_2.12
[error] 	com.trueaccord.scalapb:scalapb-runtime_2.12
[error] 	com.trueaccord.lenses:lenses_2.12
[error] 	org.scalameta:inline_2.12
[error] 	com.lihaoyi:scalaparse_2.12
[error] 	org.scala-lang.modules:scala-parser-combinators_2.12
[error] 	org.scala-sbt:librarymanagement-core_2.12
[error] 	org.scala-lang.modules:scala-xml_2.12
[error] 	org.scala-sbt:util-tracking_2.12
[error] 	org.scala-sbt:launcher-interface
[error] 	org.scala-sbt:util-cache_2.12
[error] 	org.scala-sbt:util-logging_2.12
[error] 	org.scala-sbt:util-interface
[error] 	org.scala-sbt:util-control_2.12
[error] 	org.scala-sbt:io_2.12
[error] 	org.scala-sbt:util-relation_2.12
[error] 	org.scala-sbt:util-position_2.12
[error] Use 'last' for the full log.
Project loading failed: (r)
</details>etry, (q)uit, (l)ast, or (i)gnore?

```

</details>

<details>
  <summary>
    Detailed error message with sbt 1.3.13:
  </summary>

```
[error] java.lang.NoClassDefFoundError: scala/meta/prettyprinters/Options
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:57)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:151)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:147)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:210)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:57)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1299)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1244)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1223)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1202)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:688)
[error] 	at sbt.internal.Load$.timed(Load.scala:1376)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:688)
[error] 	at sbt.internal.Load$.timed(Load.scala:1376)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:682)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:480)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:542)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:558)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:488)
[error] 	at sbt.internal.Load$.load(Load.scala:467)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:243)
[error] 	at sbt.internal.Load$.timed(Load.scala:1376)
[error] 	at sbt.internal.Load$.apply(Load.scala:243)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:55)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:847)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:847)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:801)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:149)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:144)
[error] 	at sbt.Command$.process(Command.scala:187)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:199)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:235)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:147)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:147)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:147)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:138)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:116)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:110)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:132)
[error] 	at sbt.xMain$.run(Main.scala:67)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
[error] 	at sbt.xMain.run(Main.scala:39)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.ClassNotFoundException: scala.meta.prettyprinters.Options
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:57)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:151)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:147)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:210)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:57)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1299)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1244)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1223)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1202)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:688)
[error] 	at sbt.internal.Load$.timed(Load.scala:1376)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:688)
[error] 	at sbt.internal.Load$.timed(Load.scala:1376)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:682)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:480)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:542)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:558)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:488)
[error] 	at sbt.internal.Load$.load(Load.scala:467)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:243)
[error] 	at sbt.internal.Load$.timed(Load.scala:1376)
[error] 	at sbt.internal.Load$.apply(Load.scala:243)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:55)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:847)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:847)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:801)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:149)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:144)
[error] 	at sbt.Command$.process(Command.scala:187)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:199)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:235)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:147)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:147)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:147)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:138)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:116)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:110)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:132)
[error] 	at sbt.xMain$.run(Main.scala:67)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
[error] 	at sbt.xMain.run(Main.scala:39)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: scala/meta/prettyprinters/Options
[error] Use 'last' for the full log.
[debug] > Exec(loadFailed, None, None)
[debug] > Exec(last, None, None)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

```

</details>

**Comment by tkawachi** [comment]
Thank you for reporting @ciuncan.

Since sbt-doctest depends on scalameta since 0.9.0, you will get an error if you have another sbt plugin that depends on incompatible scalameta. Check `~/.sbt/1.0/plugins/*.sbt` for such a plugin.

see https://github.com/tkawachi/sbt-doctest#compatibility-with-other-sbt-plugins

**Comment by ciuncan** [comment]
Hi @tkawachi , thank you for the quick response. I thought I read the readme thoroughly, but that part somehow escaped my attention, sorry. 

Indeed, I had this sole plugin in my `~/.sbt/1.0/plugins/build.sbt` [sbt-ammonite-classpath](https://github.com/ThoughtWorksInc/sbt-ammonite-classpath). If I remove this one, and enable all others, sbt do not fail.

I checked the dependency graph of `sbt-ammonite-classpath`, it is depending on `org.scalameta:scalameta_2.12:1.7.0`. `sbt-doctest` appear to be using scalameta version 4, since `sbt-ammonite-classpath` is using an older version, I'll have to look for a solution there, right?

**Comment by tkawachi** [comment]
The latest version of Scalameta at the moment is 4.3.21, so I think it would be a good idea to use 4.x.x in both plugin.

I'll close this issue, but feel free to reopen it if you want to continue communicating with it.
